name: Continuous Integration

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          sudo apt -q install libsdl2-dev
        elif [ "$RUNNER_OS" = "macOS" ]; then
          brew install sdl2
        fi
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
