name: Continuous Integration

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL
      run: sudo apt -q install libsdl2-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check

  macos_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL
      run: brew install sdl2 autoconf automake libtool
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
